---
- name: install nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes
  notify: start nginx

- name: add site config
  copy:
    src: jenkins.morganj.co.uk.conf
    dest: /etc/nginx/sites-enabled/jenkins.morganj.co.uk.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
