---
# tasks file for dockerce
- name: install prerequisites
  apt:
    name:
      - apt-transport-https
      - curl
      - ca-certificates
      - software-properties-common
    state: latest

- name: add docker gpg key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: add docker registery to apt sources
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  notify: apt update

- name: install docker
  apt:
    name: docker-ce
    state: latest

- name: add jenkins to docker group
  user:
    name: jenkins
    groups: docker
    state: present
  register: jenkinsuser

- name: reboot host vm
  reboot:
    reboot_timeout: 3600
  when: jenkinsuser.changed

# a reboot of the vm is required for this to complete
