---
- name: install software properties common
  apt:
    name: software-properties-common
    update_cache: yes
    state: latest

- name: add universe repository
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu bionic universe

- name: add certbot repository
  apt_repository:
    repo: ppa:certbot/certbot
  notify: apt update

- name: install certbot
  apt:
    name: certbot
    state: latest

- name: install certbot nginx
  apt:
    name: python-certbot-nginx
    state: latest

- name: get certificates
  shell: certbot --nginx -n -m {{email}} --agree-tos --redirect --domains {{domains}}
